backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog-en"
    label: "Blog - EN"
    folder: "src/pages/blog/en"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Locale", name: "locale", widget: "hidden", default: "en"}
      - {label: "Page Key", name: "pageKey", widget: "hidden", default: "page_blogpost"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "blog-de"
    label: "Blog - DE"
    folder: "src/pages/blog/de"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Locale", name: "locale", widget: "hidden", default: "de"}
      - {label: "Page Key", name: "pageKey", widget: "hidden", default: "page_blogpost"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home - EN"
        name: "home"
        file: "src/pages/home/index.md"
        fields:
          - {label: "Page Key", name: "pageKey", widget: "hidden", default: "page_home"}
          - {label: "Locale", name: "locale", widget: "hidden", default: "en"}
          - {label: "SEO Title", name: "seo_title", widget: "string"}
          - {label: "SEO Description", name: "seo_desc", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Text", name: "text", widget: "text"}
      - label: "Home - DE"
        name: "home"
        file: "src/pages/home/index.de.md"
        fields:
          - {label: "Page Key", name: "pageKey", widget: "hidden", default: "page_home"}
          - {label: "Locale", name: "locale", widget: "hidden", default: "de"}
          - {label: "SEO Title", name: "seo_title", widget: "string"}
          - {label: "SEO Description", name: "seo_desc", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Text", name: "text", widget: "text"}
